/**
 * Programmatic SEO topic matrix for Maple Insight.
 *
 * Each entry defines one article to generate. Feed this to batch-generate.mjs.
 *
 * @typedef {Object} TopicEntry
 * @property {string}      slug           - URL slug and filename (must be unique)
 * @property {string}      title          - Article title and frontmatter title
 * @property {string}      topic          - Description sent to AI to guide generation
 * @property {string}      category       - Frontmatter category: Taxes | Savings | Newcomers
 * @property {string[]}    tags           - Frontmatter tags
 * @property {string[]}    keywords       - SEO keywords woven into the article
 * @property {string}      calculatorLink - Relative URL to the relevant calculator
 * @property {string}      calculatorCta  - Button text for the calculator CTA
 * @property {number|null} incomeLevel    - Income focus in CAD, or null
 * @property {string|null} province       - Province focus, or null
 * @property {string}      description    - Frontmatter meta description
 */

export const TOPIC_MATRIX = [
  // ── Income-specific RRSP refund articles ($40k–$150k, every $10k) ────────────
  {
    slug: "rrsp-refund-40k-income-canada",
    title: "RRSP Refund for $40,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $40,000 per year can expect, including worked tax bracket examples",
    category: "Taxes",
    tags: ["rrsp refund", "low income", "canada taxes", "40000 income"],
    keywords: ["RRSP refund $40k", "RRSP tax refund low income Canada", "RRSP $40000 income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 40000,
    province: null,
    description: "Wondering how much RRSP refund you get on a $40,000 salary? See exactly how tax brackets work at this income level with real 2025 numbers.",
  },
  {
    slug: "rrsp-refund-50k-income-canada",
    title: "RRSP Refund for $50,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $50,000 per year can expect, with worked examples using 2025 federal and Ontario tax brackets",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "50000 income"],
    keywords: ["RRSP refund $50k", "RRSP tax refund 50000 Canada", "RRSP 50k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 50000,
    province: null,
    description: "On a $50,000 income, your RRSP refund depends on your marginal tax rate. Here is the exact math for 2025.",
  },
  {
    slug: "rrsp-refund-60k-income-canada",
    title: "RRSP Refund for $60,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $60,000 per year can expect, including the impact of straddling the 20.5% federal bracket",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "60000 income"],
    keywords: ["RRSP refund $60k", "RRSP tax refund 60000 Canada", "RRSP 60k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 60000,
    province: null,
    description: "At $60,000 income you sit near an important federal tax bracket. See how RRSP contributions reduce your 2025 tax bill.",
  },
  {
    slug: "rrsp-refund-70k-income-canada",
    title: "RRSP Refund for $70,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $70,000 per year can expect, with step-by-step 2025 federal and Ontario tax bracket calculation",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "70000 income"],
    keywords: ["RRSP refund $70k", "RRSP tax refund 70000 Canada", "RRSP 70k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 70000,
    province: null,
    description: "Earning $70,000 in Canada? Here is exactly how much RRSP refund you can expect using 2025 federal and Ontario tax brackets.",
  },
  {
    slug: "rrsp-refund-80k-income-canada",
    title: "RRSP Refund for $80,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $80,000 per year can expect, with detailed 2025 bracket math and contribution strategy tips",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "80000 income"],
    keywords: ["RRSP refund $80k", "RRSP tax refund 80000 Canada", "RRSP 80k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 80000,
    province: null,
    description: "At $80,000 income your marginal tax rate is around 31.5% combined. See how RRSP contributions translate into real savings.",
  },
  {
    slug: "rrsp-refund-90k-income-canada",
    title: "RRSP Refund for $90,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $90,000 per year can expect, including RRSP contribution limit calculations for 2025",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "90000 income"],
    keywords: ["RRSP refund $90k", "RRSP tax refund 90000 Canada", "RRSP 90k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 90000,
    province: null,
    description: "At $90,000 income, RRSP contributions can produce a significant refund. Here is the math with real 2025 numbers.",
  },
  {
    slug: "rrsp-refund-100k-income-canada",
    title: "RRSP Refund for $100,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $100,000 per year can expect, with analysis of the 20.5% federal bracket and combined provincial rates",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "100000 income", "six figure income"],
    keywords: ["RRSP refund $100k", "RRSP tax refund 100000 Canada", "RRSP six figure income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 100000,
    province: null,
    description: "At $100,000 income, each dollar of RRSP saves you around 33 cents in tax. See the full 2025 breakdown.",
  },
  {
    slug: "rrsp-refund-110k-income-canada",
    title: "RRSP Refund for $110,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $110,000 per year can expect, including strategy for pushing income below the $114,750 federal bracket threshold",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "110000 income"],
    keywords: ["RRSP refund $110k", "RRSP tax refund 110000 Canada", "RRSP bracket optimization 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 110000,
    province: null,
    description: "At $110,000 income you are close to the next federal bracket. Here is how RRSP contributions can keep you in a lower bracket.",
  },
  {
    slug: "rrsp-refund-120k-income-canada",
    title: "RRSP Refund for $120,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $120,000 per year can expect, now in the 26% federal bracket, with full 2025 calculation",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "120000 income", "high income"],
    keywords: ["RRSP refund $120k", "RRSP tax refund 120000 Canada", "RRSP high income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 120000,
    province: null,
    description: "At $120,000 income you are in the 26% federal bracket. RRSP contributions now save you more per dollar than ever.",
  },
  {
    slug: "rrsp-refund-130k-income-canada",
    title: "RRSP Refund for $130,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $130,000 per year can expect, with combined federal and Ontario rates and maximum contribution strategy",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "130000 income", "high income"],
    keywords: ["RRSP refund $130k", "RRSP tax refund 130000 Canada", "RRSP $130k income 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 130000,
    province: null,
    description: "At $130,000 income your combined marginal rate is around 43%. See how RRSP contributions generate your biggest possible refund.",
  },
  {
    slug: "rrsp-refund-140k-income-canada",
    title: "RRSP Refund for $140,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $140,000 per year can expect, with analysis of maxing out the 2025 RRSP contribution limit of $32,490",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "140000 income", "high income"],
    keywords: ["RRSP refund $140k", "RRSP tax refund 140000 Canada", "max RRSP contribution 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 140000,
    province: null,
    description: "At $140,000 income, maxing out your RRSP can generate a refund of over $13,000. Here is the full 2025 calculation.",
  },
  {
    slug: "rrsp-refund-150k-income-canada",
    title: "RRSP Refund for $150,000 Income in Canada (2025)",
    topic: "How much RRSP refund a Canadian earning $150,000 per year can expect, at the 26% federal bracket with significant RRSP optimization opportunities",
    category: "Taxes",
    tags: ["rrsp refund", "canada taxes", "150000 income", "high income"],
    keywords: ["RRSP refund $150k", "RRSP tax refund 150000 Canada", "RRSP high earner 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Refund",
    incomeLevel: 150000,
    province: null,
    description: "Earning $150,000? RRSP is one of the most powerful tax tools available to you. See the 2025 savings breakdown.",
  },

  // ── Province-specific RRSP articles ─────────────────────────────────────────
  {
    slug: "rrsp-refund-ontario-2025",
    title: "RRSP Tax Refund for Ontario Residents (2025)",
    topic: "Province-specific RRSP refund calculations for Ontario residents using 2025 federal and Ontario provincial tax brackets, with worked examples at multiple income levels",
    category: "Taxes",
    tags: ["rrsp ontario", "ontario taxes", "rrsp refund ontario 2025"],
    keywords: ["RRSP refund Ontario 2025", "Ontario tax bracket 2025", "RRSP Ontario income tax refund"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: "Ontario",
    description: "Ontario-specific RRSP refund guide with 2025 provincial and federal tax brackets. See how much you save at your income level.",
  },
  {
    slug: "rrsp-refund-bc-2025",
    title: "RRSP Tax Refund for BC Residents (2025)",
    topic: "Province-specific RRSP refund calculations for British Columbia residents using 2025 federal and BC provincial tax brackets, compared to Ontario",
    category: "Taxes",
    tags: ["rrsp bc", "bc taxes", "rrsp refund bc 2025"],
    keywords: ["RRSP refund BC 2025", "British Columbia RRSP refund", "BC tax bracket 2025 RRSP"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: "BC",
    description: "How RRSP contributions reduce your taxes as a BC resident. Full 2025 provincial brackets and worked examples.",
  },
  {
    slug: "rrsp-refund-alberta-2025",
    title: "RRSP Tax Refund for Alberta Residents (2025)",
    topic: "Province-specific RRSP refund in Alberta — Alberta has a relatively low provincial rate starting at 10%, making combined marginal rates the lowest of major provinces, with 2025 worked examples",
    category: "Taxes",
    tags: ["rrsp alberta", "alberta taxes", "rrsp refund alberta 2025"],
    keywords: ["RRSP refund Alberta 2025", "Alberta tax RRSP refund", "Alberta 2025 income tax RRSP"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: "Alberta",
    description: "Alberta starts at a 10% provincial rate — one of the lowest in Canada. Here is how that affects your RRSP refund in 2025.",
  },
  {
    slug: "rrsp-refund-quebec-2025",
    title: "RRSP Tax Refund for Quebec Residents (2025)",
    topic: "Province-specific RRSP refund for Quebec residents — Quebec has its own provincial tax return (TP-1), higher provincial rates, and a federal abatement, with 2025 worked examples using Quebec brackets",
    category: "Taxes",
    tags: ["rrsp quebec", "quebec taxes", "rrsp refund quebec 2025", "reer remboursement"],
    keywords: ["RRSP refund Quebec 2025", "REER Quebec remboursement", "Quebec tax bracket 2025 RRSP", "Quebec TP-1 RRSP"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: "Quebec",
    description: "Quebec RRSP (REER) refund explained with 2025 provincial tax brackets, the federal abatement, and the separate TP-1 return.",
  },

  // ── Newcomer-specific articles ───────────────────────────────────────────────
  {
    slug: "rrsp-for-newcomers-first-year-canada",
    title: "RRSP for Newcomers to Canada: Your First Year Guide (2025)",
    topic: "Complete guide for immigrants and newcomers to Canada on opening and using RRSP in their first tax year — when RRSP room starts accumulating, how to open an account, and what refund to expect",
    category: "Newcomers",
    tags: ["newcomers canada", "rrsp immigrants", "first year canada taxes", "new immigrant rrsp"],
    keywords: ["RRSP newcomers Canada 2025", "new immigrant RRSP first year", "RRSP first year Canada", "newcomer tax refund Canada"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Estimate Your First RRSP Refund",
    incomeLevel: null,
    province: null,
    description: "New to Canada? Learn exactly when RRSP room starts, how to open an account, and what tax refund to expect in your first year.",
  },
  {
    slug: "rrsp-contribution-room-newcomers-canada",
    title: "How RRSP Contribution Room Works for New Immigrants to Canada",
    topic: "How RRSP contribution room accumulates for people who recently moved to Canada — the CRA rules, when room starts, how to check your limit, and how to maximize it as a newcomer",
    category: "Newcomers",
    tags: ["rrsp contribution room", "newcomers canada", "immigration canada rrsp", "cra rrsp limit"],
    keywords: ["RRSP room newcomers Canada", "RRSP contribution limit new immigrant", "CRA RRSP room immigration", "check RRSP room Canada"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: null,
    description: "RRSP room for newcomers only starts after filing your first Canadian tax return. Here is exactly how it works and how to maximize it.",
  },
  {
    slug: "rrsp-vs-tfsa-newcomers-canada-strategy",
    title: "RRSP vs TFSA for Newcomers to Canada: Which Should You Use First?",
    topic: "Comparing RRSP and TFSA for new immigrants to Canada — which account to prioritize based on income, residency length, plans to return home, and long-term goals",
    category: "Newcomers",
    tags: ["rrsp vs tfsa newcomers", "newcomers canada savings", "tfsa immigrants canada"],
    keywords: ["RRSP TFSA newcomer Canada", "immigrant TFSA RRSP priority", "new to Canada savings accounts RRSP TFSA"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Benefit",
    incomeLevel: null,
    province: null,
    description: "Should newcomers to Canada prioritize RRSP or TFSA? A practical guide based on income level, plans, and timeline.",
  },

  // ── Tax refund scenario articles ─────────────────────────────────────────────
  {
    slug: "canada-tax-refund-first-job",
    title: "Getting a Tax Refund on Your First Job in Canada (2025)",
    topic: "How taxes and refunds work for someone starting their first job in Canada — understanding the T4, source deductions, RRSP deductions, and how to file to get the maximum refund",
    category: "Taxes",
    tags: ["first job canada", "canada tax refund", "t4 canada", "first tax return canada"],
    keywords: ["Canada tax refund first job 2025", "first T4 Canada tax refund", "new employee tax refund Canada", "how to get tax refund Canada first job"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Deduction",
    incomeLevel: null,
    province: null,
    description: "Starting your first job in Canada? This guide explains exactly how income tax works, what to do with your T4, and how to maximize your refund.",
  },
  {
    slug: "freelancer-self-employed-tax-refund-canada",
    title: "Tax Refund for Freelancers and Self-Employed Canadians (2025)",
    topic: "How Canadian freelancers and self-employed workers handle taxes, RRSP deductions, business expense deductions, and quarterly installments to maximize refunds and minimize tax owing",
    category: "Taxes",
    tags: ["freelancer canada taxes", "self-employed tax refund canada", "canada self employed rrsp 2025"],
    keywords: ["freelancer tax refund Canada 2025", "self employed RRSP Canada", "Canada self employed tax deduction", "freelance taxes Canada guide"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Estimate Your RRSP Refund as a Freelancer",
    incomeLevel: null,
    province: null,
    description: "Self-employed in Canada? Learn how RRSP and business deductions interact to significantly reduce your tax bill in 2025.",
  },
  {
    slug: "part-time-worker-tax-refund-canada",
    title: "Tax Refund for Part-Time Workers in Canada (2025)",
    topic: "How income tax refunds work for Canadians who work part-time — including students, parents returning to work, and people holding multiple jobs — with 2025 bracket examples",
    category: "Taxes",
    tags: ["part time worker canada taxes", "part time tax refund canada", "low income canada refund"],
    keywords: ["part time worker tax refund Canada 2025", "part time job Canada taxes refund", "tax refund part time income Canada"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Try the RRSP Refund Calculator",
    incomeLevel: null,
    province: null,
    description: "Part-time workers in Canada are often entitled to a tax refund. Here is how the system works and how RRSP can help boost it.",
  },
  {
    slug: "rrsp-refund-ontario-vs-bc",
    title: "RRSP Refund: Ontario vs BC — Which Province Saves More? (2025)",
    topic: "Comparing RRSP refund amounts between Ontario and BC residents at income levels from $60,000 to $150,000 — showing how different provincial tax brackets affect the same RRSP contribution",
    category: "Taxes",
    tags: ["rrsp refund ontario vs bc", "ontario vs bc taxes rrsp", "province tax comparison canada"],
    keywords: ["RRSP refund Ontario vs BC 2025", "Ontario BC tax comparison RRSP", "which province better RRSP refund Canada"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your Province-Specific Refund",
    incomeLevel: null,
    province: null,
    description: "Ontario and BC have different provincial tax brackets. See how the same RRSP contribution produces different refunds in each province.",
  },

  // ── TFSA vs RRSP comparison articles ────────────────────────────────────────
  {
    slug: "rrsp-vs-tfsa-high-income-canada",
    title: "RRSP vs TFSA for High Earners in Canada ($100k+) — 2025 Guide",
    topic: "Why high-income Canadians earning $100,000 or more typically benefit more from RRSP than TFSA, with worked dollar-for-dollar comparison examples using 2025 tax rates",
    category: "Savings",
    tags: ["rrsp vs tfsa high income", "high earner canada rrsp", "100k income rrsp vs tfsa"],
    keywords: ["RRSP vs TFSA high income Canada 2025", "RRSP 100k salary Canada", "TFSA RRSP high earner comparison 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Advantage",
    incomeLevel: 100000,
    province: null,
    description: "Earning over $100k? RRSP usually beats TFSA at high incomes thanks to the tax refund. Here is the 2025 math explained simply.",
  },
  {
    slug: "rrsp-vs-tfsa-low-income-canada",
    title: "RRSP vs TFSA for Lower Income Canadians (Under $50k) — 2025",
    topic: "Why lower-income Canadians earning under $50,000 often benefit more from TFSA than RRSP — including the GIS clawback risk, lower tax bracket implications, and when RRSP still makes sense",
    category: "Savings",
    tags: ["rrsp vs tfsa low income canada", "low income canada savings", "tfsa low income canada 2025"],
    keywords: ["TFSA vs RRSP low income Canada 2025", "RRSP low income Canada refund", "TFSA better than RRSP low income Canada"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "See Your RRSP Refund Math",
    incomeLevel: 45000,
    province: null,
    description: "At lower incomes, TFSA often makes more sense than RRSP. This 2025 guide explains exactly when and why with real numbers.",
  },
  {
    slug: "rrsp-and-tfsa-both-same-year-canada",
    title: "Can You Contribute to Both RRSP and TFSA in the Same Year? (Canada)",
    topic: "Explaining that Canadians can contribute to both RRSP and TFSA in the same tax year — and how to strategically allocate money between them based on income, age, and retirement plans",
    category: "Savings",
    tags: ["rrsp and tfsa same year", "both accounts canada", "maximize savings canada rrsp tfsa"],
    keywords: ["RRSP and TFSA same year Canada", "contribute both RRSP TFSA Canada", "RRSP TFSA strategy Canada 2025"],
    calculatorLink: "/tools/rrsp-refund",
    calculatorCta: "Calculate Your RRSP Savings",
    incomeLevel: null,
    province: null,
    description: "Yes, you can use both RRSP and TFSA in the same year. Here is a practical strategy for Canadians at any income level.",
  },
];
