import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalPageLayout,
  LegalSection,
  LegalP,
  LegalUL,
  LegalLI,
} from "@/components/LegalPageLayout";

export const metadata: Metadata = {
  title: "Privacy Policy | Maple Insight Canada",
  description:
    "Learn how Maple Insight Canada collects, uses, and protects your personal information, including newsletter data, analytics, and local storage usage.",
  robots: { index: true, follow: true },
  alternates: { canonical: "https://mapleinsight.ca/privacy" },
};

const LAST_UPDATED = "March 17, 2026";

export default function PrivacyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated={LAST_UPDATED}>

      <LegalSection title="1. Introduction">
        <LegalP>
          Maple Insight Canada (&ldquo;Maple Insight,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;) operates the website mapleinsight.ca (the &ldquo;Site&rdquo;). We are a
          Canadian personal finance education platform focused on helping newcomers to Canada
          understand and navigate topics such as taxes, budgeting, savings accounts, and
          government benefits.
        </LegalP>
        <LegalP>
          This Privacy Policy describes what information we collect, how we use it, and the choices
          you have. By using the Site, you agree to the practices described in this policy. If you
          do not agree, please discontinue use of the Site.
        </LegalP>
      </LegalSection>

      <LegalSection title="2. Information We Collect">
        <LegalP><strong>a) Information you provide to us</strong></LegalP>
        <LegalUL>
          <LegalLI>
            <strong>Email address and first name (optional)</strong> — When you subscribe to the
            Maple Insight newsletter or download a lead magnet resource, we collect your email
            address and, optionally, your first name. You provide this information voluntarily.
          </LegalLI>
        </LegalUL>

        <LegalP><strong>b) Information collected automatically</strong></LegalP>
        <LegalUL>
          <LegalLI>
            <strong>Analytics data</strong> — When you visit the Site, we collect information
            automatically through Google Analytics 4 (GA4) and Google Tag Manager (GTM). This
            includes your approximate geographic location (derived from an anonymized or truncated
            IP address), device type, browser type and version, pages visited, time spent on each
            page, referral source, and general navigation behavior. We do not collect or store your
            full IP address.
          </LegalLI>
          <LegalLI>
            <strong>Usage events</strong> — We track interactions with our interactive tools,
            including financial simulator steps completed, calculators used, and roadmap tasks
            checked. This data is collected in aggregate to help us improve the Site and is not
            tied to your identity.
          </LegalLI>
        </LegalUL>

        <LegalP><strong>c) Information stored locally in your browser</strong></LegalP>
        <LegalUL>
          <LegalLI>
            <strong>Checklist progress</strong> — Your newcomer checklist progress (which items
            you have checked off) is stored in your browser&apos;s <code>localStorage</code>. This
            data never leaves your device and is not transmitted to our servers.
          </LegalLI>
          <LegalLI>
            <strong>Province preference and calculator inputs</strong> — Your selected province and
            any financial simulator inputs you provide are stored in browser session or local
            storage to preserve your session. This data is not transmitted to Maple Insight servers
            or shared with third parties.
          </LegalLI>
          <LegalLI>
            <strong>Financial report</strong> — Results generated by the Canada Financial Simulator
            are stored in your browser&apos;s <code>localStorage</code> for the duration of your
            session. This data is not accessible to Maple Insight and is deleted when you clear
            your browser storage.
          </LegalLI>
        </LegalUL>
      </LegalSection>

      <LegalSection title="3. How We Use Your Information">
        <LegalP>We use the information we collect for the following purposes:</LegalP>
        <LegalUL>
          <LegalLI>
            To send you the Maple Insight newsletter and any lead magnet content you requested
            (email address).
          </LegalLI>
          <LegalLI>
            To understand how users interact with our content so we can improve articles,
            calculators, and tools (analytics data).
          </LegalLI>
          <LegalLI>
            To understand aggregate usage patterns and identify which content is most valuable to
            our audience (analytics data).
          </LegalLI>
          <LegalLI>
            To personalize calculator defaults, such as pre-selecting your province (localStorage).
          </LegalLI>
          <LegalLI>
            To fulfill legal obligations or enforce our Terms of Use if required.
          </LegalLI>
        </LegalUL>
        <LegalP>
          We do not sell, rent, or trade your personal information to third parties for their
          marketing purposes.
        </LegalP>
      </LegalSection>

      <LegalSection title="4. Cookies and Tracking Technologies">
        <LegalP>
          The Site uses cookies and similar tracking technologies for analytics purposes only. We
          do not use advertising cookies or participate in behavioral advertising networks.
        </LegalP>
        <LegalP>
          <strong>Google Analytics 4 and Google Tag Manager:</strong> These services set cookies
          in your browser to track how you interact with the Site. The data collected is
          transmitted to Google servers and is subject to{" "}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "#1B7A4A" }}
          >
            Google&apos;s Privacy Policy
          </a>
          . We have configured GA4 to anonymize IP addresses to the extent technically possible.
        </LegalP>
        <LegalP>
          <strong>Opting out of analytics:</strong> You can prevent Google Analytics from tracking
          you by installing the{" "}
          <a
            href="https://tools.google.com/dlpage/gaoptout"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "#1B7A4A" }}
          >
            Google Analytics Opt-out Browser Add-on
          </a>
          . You can also adjust your browser&apos;s cookie settings to block or delete cookies at
          any time.
        </LegalP>
        <LegalP>
          <strong>Essential functionality:</strong> We use browser <code>localStorage</code> (not
          cookies) to save your progress in the newcomer checklist and financial simulator. This is
          a local browser feature that does not involve any server communication.
        </LegalP>
      </LegalSection>

      <LegalSection title="5. Third-Party Services">
        <LegalP>
          Maple Insight uses the following third-party services that may receive limited
          information about your visit:
        </LegalP>
        <LegalUL>
          <LegalLI>
            <strong>Sanity CMS</strong> — Our articles and editorial content are stored and served
            through Sanity (sanity.io). When you load an article, your browser may make a request
            to Sanity&apos;s content delivery network. Sanity may log standard web request data
            such as your IP address. Refer to{" "}
            <a
              href="https://www.sanity.io/legal/privacy"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#1B7A4A" }}
            >
              Sanity&apos;s Privacy Policy
            </a>{" "}
            for details.
          </LegalLI>
          <LegalLI>
            <strong>Google Analytics 4 / Google Tag Manager</strong> — As described in Section 4,
            Google receives analytics data about your session. Google may process and store this
            data on its own infrastructure.
          </LegalLI>
          <LegalLI>
            <strong>Email marketing platform</strong> — When you subscribe to our newsletter, your
            email address and name are transmitted to and stored by our email marketing provider
            (such as Mailchimp, ConvertKit, or Buttondown). You can unsubscribe at any time using
            the link in any email we send you, and your data will be removed from our mailing list.
          </LegalLI>
          <LegalLI>
            <strong>Affiliate partners</strong> — When you click an affiliate link on the Site
            (for example, to Wealthsimple, Questrade, TurboTax, or other financial products), you
            will be directed to the third-party website. Maple Insight does not share your personal
            information with affiliate partners. The affiliate partner may set their own cookies
            or collect data in accordance with their own privacy policies.
          </LegalLI>
          <LegalLI>
            <strong>Vercel</strong> — The Site is hosted on Vercel, which may log standard server
            access data including IP addresses for infrastructure and security purposes. Refer to{" "}
            <a
              href="https://vercel.com/legal/privacy-policy"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#1B7A4A" }}
            >
              Vercel&apos;s Privacy Policy
            </a>{" "}
            for details.
          </LegalLI>
        </LegalUL>
      </LegalSection>

      <LegalSection title="6. Affiliate Disclosure">
        <LegalP>
          Some links on this Site are affiliate links. If you click through an affiliate link and
          make a purchase or open an account, Maple Insight may earn a commission from the partner
          at no additional cost to you. Affiliate relationships do not influence which products or
          services we recommend, nor do they affect the editorial independence of our content.
        </LegalP>
        <LegalP>
          For full details, see our{" "}
          <Link href="/affiliate-disclosure" style={{ color: "#1B7A4A" }}>
            Affiliate Disclosure page
          </Link>
          .
        </LegalP>
      </LegalSection>

      <LegalSection title="7. Data Retention">
        <LegalUL>
          <LegalLI>
            <strong>Email addresses:</strong> Retained on our email marketing platform until you
            unsubscribe or request deletion. Upon unsubscribe, your address is removed from active
            mailing lists. You may request permanent deletion by contacting us (see Section 11).
          </LegalLI>
          <LegalLI>
            <strong>Analytics data:</strong> Retained by Google according to the retention settings
            we have configured in Google Analytics (typically 14 months). We do not export or
            store raw analytics data independently.
          </LegalLI>
          <LegalLI>
            <strong>Browser localStorage data:</strong> Persists in your browser until you clear
            your browser storage or use the &ldquo;Start Over&rdquo; or reset functions within the
            relevant tools. Maple Insight has no ability to delete data stored in your browser.
          </LegalLI>
        </LegalUL>
      </LegalSection>

      <LegalSection title="8. Your Rights">
        <LegalP>
          Depending on your jurisdiction and applicable privacy laws, you may have the following
          rights regarding your personal information:
        </LegalP>
        <LegalUL>
          <LegalLI>
            <strong>Right to access:</strong> You may request a copy of the personal information
            we hold about you (primarily your email address).
          </LegalLI>
          <LegalLI>
            <strong>Right to correction:</strong> You may request that inaccurate information be
            corrected.
          </LegalLI>
          <LegalLI>
            <strong>Right to deletion:</strong> You may request that we delete your personal
            information. For newsletter subscribers, this means removal from our mailing list and
            deletion of your contact record from our email platform.
          </LegalLI>
          <LegalLI>
            <strong>Right to unsubscribe:</strong> Every email we send includes an unsubscribe
            link. You may opt out at any time.
          </LegalLI>
          <LegalLI>
            <strong>Right to withdraw consent:</strong> Where we rely on your consent to process
            your data (e.g., newsletter signup), you may withdraw consent at any time.
          </LegalLI>
        </LegalUL>
        <LegalP>
          To exercise any of these rights, contact us at the email address in Section 11.
        </LegalP>
      </LegalSection>

      <LegalSection title="9. Children's Privacy">
        <LegalP>
          The Site is not directed at children under the age of 13, and we do not knowingly
          collect personal information from children under 13. If you believe a child under 13 has
          provided us with personal information, please contact us and we will take steps to delete
          such information.
        </LegalP>
      </LegalSection>

      <LegalSection title="10. Changes to This Privacy Policy">
        <LegalP>
          We may update this Privacy Policy from time to time to reflect changes in our practices,
          legal requirements, or the services we offer. When we make material changes, we will
          update the &ldquo;Last updated&rdquo; date at the top of this page. We encourage you to
          review this policy periodically. Continued use of the Site after any changes constitutes
          your acceptance of the revised policy.
        </LegalP>
      </LegalSection>

      <LegalSection title="11. Contact Information">
        <LegalP>
          If you have questions about this Privacy Policy, wish to exercise your data rights, or
          want to report a privacy concern, please contact us at:
        </LegalP>
        <LegalP>
          <strong>Email:</strong>{" "}
          <a href="mailto:privacy@mapleinsight.ca" style={{ color: "#1B7A4A" }}>
            privacy@mapleinsight.ca
          </a>
        </LegalP>
        <LegalP>
          We will respond to privacy-related requests within 30 days.
        </LegalP>
      </LegalSection>

    </LegalPageLayout>
  );
}
